### ISSUE TITLE
More natural moving of the robots

### ISSUE THREAD

**Issue by docbensch** [rubo77/Robotoyard#6]
When showing the solution (or own moving), the speed of the robots shouldn't be linear. I would prefer to have the same time for every move, whether it's a short or a long move. It's better for counting. Like tick tick tick tick... Maybe every move with accelerate and decelerate, and every move 0,5 seconds or so.

**Comment by rubo77** [comment]
fixed in ec7a066713d51d191337967bec53dd53e7f22b8d
